export default {
  "login": "pushpakumari5117",
  "id": 68471073,
  "node_id": "MDQ6VXNlcjY4NDcxMDcz",
  "avatar_url": "https://avatars.githubusercontent.com/u/68471073?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/pushpakumari5117",
  "html_url": "https://github.com/pushpakumari5117",
  "followers_url": "https://api.github.com/users/pushpakumari5117/followers",
  "following_url": "https://api.github.com/users/pushpakumari5117/following{/other_user}",
  "gists_url": "https://api.github.com/users/pushpakumari5117/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/pushpakumari5117/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/pushpakumari5117/subscriptions",
  "organizations_url": "https://api.github.com/users/pushpakumari5117/orgs",
  "repos_url": "https://api.github.com/users/pushpakumari5117/repos",
  "events_url": "https://api.github.com/users/pushpakumari5117/events{/privacy}",
  "received_events_url": "https://api.github.com/users/pushpakumari5117/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Pushpa Kumari",
  "company": null,
  "blog": "https://pushpakumari5117.github.io/pushpaPortfolio/index.html",
  "location": "Kolkata, West Bengal",
  "email": null,
  "hireable": null,
  "bio": "Loves coding.\r\nMERN enthusiast.\r\n",
  "twitter_username": null,
  "public_repos": 43,
  "public_gists": 0,
  "followers": 63,
  "following": 1,
  "created_at": "2020-07-18T14:08:52Z",
  "updated_at": "2021-06-01T17:11:55Z"
};